name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to hub
        env:
          # This uses the secret you named 'HF'
          HF_SECRET: ${{ secrets.HF }}
        run: |
          git push --force https://x-token:$HF_SECRET@huggingface.co/spaces/Silvester01/Titan-review-software main